### PR TITLE
Added Solution to Problem 20.

### PR DESCRIPTION
**Pull request by HarsMishra**

### CODE REVIEW

**Comment by thisispratt** [comment]
@HarsMishra Please **use capital letters when using `#define`** and reformat the output a little bit. Just print the Fibonacci seq. like: 
```
0 
1 
1 
2 
3 
5 
8 
13
```
...
instead of 
```
0 1 1
1 1 2
1 2 3
2 3 5
3 5 8
5 8 13
```

**Comment by HarsMishra** [comment]
Okk. I'll do that.

**Comment by HarsMishra** [comment]
I have made the required changes.

**Comment by HarsMishra** [comment]
@thisispratt Review my PR.

**Pull request merged**
