### PR TITLE
Added the ruby folder and question 27 in ruby

### PR DESCRIPTION
**Pull request by prnvsan**

### CODE REVIEW

**Comment by thisispratt** [comment]
@prnvsan  Please rename the file to `27.rb`

**Comment by prnvsan** [comment]
I have made the requested change.

**Comment by thisispratt** [comment]
@prnvsan Your program behaves differently if the number starts with 0
For example :  `010` should return **true** as it is a palindrome but your program returns **false.**

**Comment by prnvsan** [comment]
I have made the required fix to the program.

**Pull request merged**
