### PR TITLE
Added PrimeNumberCheck-Q28 ArmstrongCheck-Q29 BinarytoDecimal&viceversa-Q38 for Java

### PR DESCRIPTION
**Pull request by VishnuRameshbabu**
I have added a program to check for prime number(q28) and to check for an Armstrong number(q29).
I have also added binary to decimal and decimal to binary conversion(q38)

### CODE REVIEW

**Comment by thisispratt** [comment]
@VishnuRameshbabu Please add only 1 file in 1 PR.

**Comment by VishnuRameshbabu** [comment]
Noted it @thisispratt  Deleted two files and left one alone. I think now there wouldn't be any issues.

**Comment by thisispratt** [comment]
@VishnuRameshbabu Please rename the `main` class to `q28`

**Comment by VishnuRameshbabu** [comment]
@thisispratt  Updated.

**Pull request merged**
