### PR TITLE
Hello world.ipynb

### PR DESCRIPTION
**Pull request by ya7sh**

### CODE REVIEW

**Comment by thisispratt** [comment]
@ya7sh Please check the code in the hello_world file.

**Comment by ya7sh** [comment]
The earlier file I uploaded was of jupyter notebook. I've also added a normal python file now. Please review it and merge it. Thank you

**Comment by thisispratt** [comment]
@ya7sh Please remove the jupyter notebook file and stick to the naming convention. (`1.py` for the first question)

**Comment by ya7sh** [comment]
I've done the required changes.

**Pull request merged**
