### PR TITLE
Update 43.cpp

### PR DESCRIPTION
**Pull request by nevergiv3up**
Added a Program to Calculate Average Using Arrays.
My first Pull request.

### CODE REVIEW

**Comment by thisispratt** [comment]
@nevergiv3up Please be more descriptive with your programs. Like the first input you are taking, Inform the user what he needs to do then take an input.

**Review by nevergiv3up — COMMENTED** [review]
I have updated the code. Please review it once again.

**Comment by thisispratt** [comment]
@nevergiv3up Please add a `cout` which informs the user that he needs to enter the length of the array.

**Comment by nevergiv3up** [comment]
Updated the code.

**Pull request merged**
