### PR TITLE
answer of 18 : Program to Find Factorial of a Number

### PR DESCRIPTION
**Pull request by Anooppandikashala**

### CODE REVIEW

**Comment by thisispratt** [comment]
@Anooppandikashala Please **stick to the naming convention**, for question 18 (rename your file as `18.py`)

**Comment by thisispratt** [comment]
@Anooppandikashala Please **change only 1 file in 1 PR.**

**Comment by Anooppandikashala** [comment]
> @Anooppandikashala Please **change only 1 file in 1 PR.**

Yes, I have renamed.

**Comment by thisispratt** [comment]
@Anooppandikashala I think you are mistaken, I said you should **only change 1 file in 1 PR**

**Comment by Anooppandikashala** [comment]
> @Anooppandikashala I think you are mistaken, I said you should **only change 1 file in 1 PR**

Ok, I will create a new PR :)

**Pull request closed without merging**
